project:
  type: website
  output-dir: docs

website:
  title: "Yeamin Faria Chowdhury"
  site-url: https://<your-username>.github.io/<your-repo>/   # optional; helps with meta tags
  search: true
  page-navigation: true
  navbar:
    logo: Image.jpg
    left:
      - text: "Home"
        href: index.qmd#top
      - text: "Analytical Samples"
        href: index.qmd#projects
      - text: "Teaching Experiences"
        href: index.qmd#teaching
      - text: "Contact"
        href: index.qmd#contact
      - text: "CV"
        href: CV-YeaminChowdhury.pdf
    right:
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/yeamin-faria-chowdhury-0b3866135/
      - icon: google-scholar
        aria-label: Google Scholar
        href: https://scholar.google.com/citations?user=k8eo0XkAAAAJ&hl=en
      - icon: envelope
        aria-label: Email
        href: mailto:yeaminfaria.chowdhury@utdallas.edu
  page-footer:
    left: "© {{< meta title >}}"

format:
  html:
    theme:
      light: minty
      dark: solar
    css: styles.css
    toc: False
    smooth-scroll: true
    anchor-sections: true
    link-external-newwindow: true
    execute:
      echo: false
